services:
    front:
        build: .
        working_dir: /app/front/dash
        ports:
            - 3000:3000
        volumes:
            - .:/app
        environment:
            - MARIADB_AUTO_UPGRADE=1
        entrypoint:
            - npm
            - start