services:
  front:
    build: .
    working_dir: /app/front/dash
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - MARIADB_AUTO_UPGRADE=1
    entrypoint:
      - npm
      - run
      - dev


  back:
    image: node:22-alpine
    working_dir: /app/back
    ports:
      - 3001:3001
    volumes:
      - .:/app
    entrypoint:
      - npx
      - tsx
      - app.ts

  db:
    image: postgres:17.0-alpine
    volumes:
      - './scripts:/dashboard-scripts'
    environment:
      TZ: UTC
      POSTGRES_DB: business
      POSTGRES_USER: business
      POSTGRES_PASSWORD: casual

  hurl:
    image: 'ghcr.io/orange-opensource/hurl:4.2.0'
    depends_on:
      - back
    working_dir: /api-tests/
    volumes:
      - './docs/request-examples:/api-tests'
    entrypoint:
      - tail
      - -f
      - /dev/null