INSERT INTO time_zones(name) VALUES('Africa/Casablanca');
INSERT INTO time_zones(name) VALUES('America/New_York');
INSERT INTO time_zones(name) VALUES('America/Los_Angeles');
INSERT INTO time_zones(name) VALUES('America/Denver');
INSERT INTO time_zones(name) VALUES('America/Sao_Paulo');
INSERT INTO time_zones(name) VALUES('Asia/Macau');
INSERT INTO time_zones(name) VALUES('Europe/Berlin');
INSERT INTO time_zones(name) VALUES('Europe/Amsterdam');

INSERT INTO cities(name, state) VALUES('New York', 'NY');
INSERT INTO cities(name, state) VALUES('Los Angeles', 'CA');
INSERT INTO cities(name, state) VALUES('Chicago', 'IL');
INSERT INTO cities(name, state) VALUES('Houston', 'TX');
INSERT INTO cities(name, state) VALUES('Phoenix', 'AZ');
INSERT INTO cities(name, state) VALUES('Philadelphia', 'PA');
INSERT INTO cities(name, state) VALUES('San Antonio', 'TX');
INSERT INTO cities(name, state) VALUES('San Diego', 'CA');
INSERT INTO cities(name, state) VALUES('Dallas', 'TX');
INSERT INTO cities(name, state) VALUES('Jacksonville', 'FL');

INSERT INTO users(email, user_role, password, time_zone) VALUES ('joe@business.com', 'ADMIN', 'q1w2e3', 5);
INSERT INTO users(email, user_role, password, time_zone) VALUES ('pam@business.com', 'USER', '123456', 3);
INSERT INTO users(email, user_role, password, time_zone) VALUES ('jim@business.com', 'USER', 'abcdef', 3);

INSERT INTO user_city_permissions(user_id, city_id) VALUES(2, 1);
INSERT INTO user_city_permissions(user_id, city_id) VALUES(2, 2);
INSERT INTO user_city_permissions(user_id, city_id) VALUES(2, 3);
INSERT INTO user_city_permissions(user_id, city_id) VALUES(2, 4);
INSERT INTO user_city_permissions(user_id, city_id) VALUES(2, 5);
INSERT INTO user_city_permissions(user_id, city_id) VALUES(3, 1);
INSERT INTO user_city_permissions(user_id, city_id) VALUES(3, 6);
INSERT INTO user_city_permissions(user_id, city_id) VALUES(3, 7);
INSERT INTO user_city_permissions(user_id, city_id) VALUES(3, 8);
INSERT INTO user_city_permissions(user_id, city_id) VALUES(3, 9);
INSERT INTO user_city_permissions(user_id, city_id) VALUES(3, 10);

INSERT INTO businesses(name, city_id, review_count) VALUES('The Odeon', 1, 73);
INSERT INTO businesses(name, city_id, review_count) VALUES('Ferdinandos Focacceria', 1, 45);
INSERT INTO businesses(name, city_id, review_count) VALUES('The Grill', 1, 12);
INSERT INTO businesses(name, city_id, review_count) VALUES('Le Coucou', 1, 78);
INSERT INTO businesses(name, city_id, review_count) VALUES('Wus Wonton King', 1, 51);
INSERT INTO businesses(name, city_id, review_count) VALUES('Bubba Gump Shrimp Co.', 2, 621);
INSERT INTO businesses(name, city_id, review_count) VALUES('Providence', 2, 941);
INSERT INTO businesses(name, city_id, review_count) VALUES('Maccheroni Republic', 2, 175);
INSERT INTO businesses(name, city_id, review_count) VALUES('71Above Restaurant and Skylounge', 2, 313);
INSERT INTO businesses(name, city_id, review_count) VALUES('El Compadre', 2, 241);
INSERT INTO businesses(name, city_id, review_count) VALUES('Smoque BBQ', 3, 121);
INSERT INTO businesses(name, city_id, review_count) VALUES('Superkhana International', 3, 185);
INSERT INTO businesses(name, city_id, review_count) VALUES('Pats Pizza and Ristorante', 3, 125);
INSERT INTO businesses(name, city_id, review_count) VALUES('Mi Tocaya Antojeria', 3, 193);
INSERT INTO businesses(name, city_id, review_count) VALUES('Lula Cafe', 3, 12);
INSERT INTO businesses(name, city_id, review_count) VALUES('Amrina', 4, 81);
INSERT INTO businesses(name, city_id, review_count) VALUES('Gatlins Fins & Feathers', 4, 31);
INSERT INTO businesses(name, city_id, review_count) VALUES('Tatemo', 4, 561);
INSERT INTO businesses(name, city_id, review_count) VALUES('Jun', 4, 167);
INSERT INTO businesses(name, city_id, review_count) VALUES('Squable', 4, 381);
INSERT INTO businesses(name, city_id, review_count) VALUES('Confluence', 5, 631);
INSERT INTO businesses(name, city_id, review_count) VALUES('Hush Public House', 5, 361);
INSERT INTO businesses(name, city_id, review_count) VALUES('Andreoli Italian Grocer', 5, 158);
INSERT INTO businesses(name, city_id, review_count) VALUES('Christophers at the Wrigley Mansion', 5, 187);
INSERT INTO businesses(name, city_id, review_count) VALUES('Hana Japanese Eatery', 5, 144);
INSERT INTO businesses(name, city_id, review_count) VALUES('Jansen', 6, 143);
INSERT INTO businesses(name, city_id, review_count) VALUES('Down North Pizza', 6, 142);
INSERT INTO businesses(name, city_id, review_count) VALUES('Cantina La Martina', 6, 147);
INSERT INTO businesses(name, city_id, review_count) VALUES('Kalaya', 6, 38);
INSERT INTO businesses(name, city_id, review_count) VALUES('Middle Child Clubhouse', 6, 538);
INSERT INTO businesses(name, city_id, review_count) VALUES('Clementine', 7, 834);
INSERT INTO businesses(name, city_id, review_count) VALUES('Demos Greek Food', 7, 38);
INSERT INTO businesses(name, city_id, review_count) VALUES('Taquitos West Avenue', 7, 85);
INSERT INTO businesses(name, city_id, review_count) VALUES('Original Donut Shop', 7, 877);
INSERT INTO businesses(name, city_id, review_count) VALUES('Nikis Tokyo Inn', 7, 87);
INSERT INTO businesses(name, city_id, review_count) VALUES('Valle', 8, 87);
INSERT INTO businesses(name, city_id, review_count) VALUES('Wrench and Rodent', 8, 568);
INSERT INTO businesses(name, city_id, review_count) VALUES('Jeune et Jolie', 8, 51);
INSERT INTO businesses(name, city_id, review_count) VALUES('Campfire', 8, 61);
INSERT INTO businesses(name, city_id, review_count) VALUES('Manna', 8, 561);
INSERT INTO businesses(name, city_id, review_count) VALUES('Harvest at the Masonic', 9, 195);
INSERT INTO businesses(name, city_id, review_count) VALUES('The Heritage Table', 9, 41);
INSERT INTO businesses(name, city_id, review_count) VALUES('Ari Korean BBQ', 9, 561);
INSERT INTO businesses(name, city_id, review_count) VALUES('Kirin Court', 9, 891);
INSERT INTO businesses(name, city_id, review_count) VALUES('Partenope Ristorante', 9, 21);
INSERT INTO businesses(name, city_id, review_count) VALUES('Mesa', 10, 81);
INSERT INTO businesses(name, city_id, review_count) VALUES('Restaurant Orsay', 10, 851);
INSERT INTO businesses(name, city_id, review_count) VALUES('Carolina Jax', 10, 14);
INSERT INTO businesses(name, city_id, review_count) VALUES('Cowford Chophouse', 10, 91);
INSERT INTO businesses(name, city_id, review_count) VALUES('Silkies Chicken and Champagne Bar', 10, 14);

UPDATE businesses SET contacted_at = '2024-01-01 00:00:00'::TIMESTAMP, contacted_by = 1 WHERE id = 1;